### ISSUE TITLE
How to remove the shadow at the end?

### ISSUE THREAD

**Issue by radianttap** [hmaidasani/RadialChartImageGenerator#1]
I think it would look visually much better if the circle would simply collapse into itself at the end, instead of having the shadowed knob.

Is there an easy way to do this or possibly set it as option?

**Comment by hmaidasani** [comment]
I will add an option to enable/disable the shadow. While I add this feature, you can go ahead and remove the shadow for yourself by downloading the project locally and editing /js/knob/jquery.knob.js and remove lines 808-822:
```
if(this.cv == this.o.max){
    c.beginPath();
    var gradient=c.createLinearGradient(this.w2,0,this.w2,this.h-this.lineWidth);
    gradient.addColorStop("0",this.o.fgColorEnd);
    gradient.addColorStop("1.0",this.o.fgColorEnd);
    c.strokeStyle = r ? gradient : this.fgColor ;

    c.shadowColor = "#555";
    c.shadowBlur    = 10;
    c.shadowOffsetX = 10; 
    c.shadowOffsetY = 0;
    c.arc(this.xy, this.xy, this.radius, this.PI2 * 1.74, a.e, a.d);

    c.stroke();
}
```

**Comment by radianttap** [comment]
Thanks for this. I actually tried, but failed to recognize where in code it should be done. Consequence of the not touching anything web-related for half a decade.

Anw, I went and created the similar generator as an iOS app, should be up on my GitHub soon.
