### ISSUE TITLE
Need @2x for iWatch

### ISSUE THREAD

**Issue by codeslubber** [hmaidasani/RadialChartImageGenerator#3]
Great job on this, thanks! However, the files all need the @2x suffix if you are going to use them with the iWatch?

**Comment by hmaidasani** [comment]
I have added a file suffix option. You can add whatever suffix you like. Test it out. Hopefully it helps. However, in my experience, I did not have to use the @2x suffix for watchkit apps.

**Comment by codeslubber** [comment]
So strange. I redid the import a bunch of times. Several times it showed
the images as 1x and sometimes as 2x. Are you putting the images into the
assets?

**Comment by hmaidasani** [comment]
I am not sure. Maybe try making the image size larger in the options and also add the @2x suffix.

**Comment by codeslubber** [comment]
[image: Inline image 1]

[image: Inline image 2]

On Sun, May 3, 2015 at 1:50 PM, Hitesh Maidasani <notifications@github.com>
wrote:

> I am not sure. Maybe try making the image size larger in the options and
> also add the @2x <https://github.com/2x> suffix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hmaidasani/RadialChartImageGenerator/issues/3#issuecomment-98543034>
> .
>



-- 
Rob Williams
*onto*metrics
Suite 102
969 Colorado Boulevard
Los Angeles, CA  90041
o: 323 284-7957

**Comment by hmaidasani** [comment]
Your images were not properly attached.

**Comment by codeslubber** [comment]
Huh? They are working fine.

On Sun, May 3, 2015 at 3:09 PM, Hitesh Maidasani <notifications@github.com>
wrote:

> Your images were not properly attached.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hmaidasani/RadialChartImageGenerator/issues/3#issuecomment-98549850>
> .
>



-- 
Rob Williams
*onto*metrics
Suite 102
969 Colorado Boulevard
Los Angeles, CA  90041
o: 323 284-7957
