### ISSUE TITLE
Remove background completely

### ISSUE THREAD

**Issue by DevManifest** [hmaidasani/RadialChartImageGenerator#7]
It would be great to have possibility to completely remove the background. Currently if Background Thickness is specified as 0, the background is still visible.

**Comment by MattKiazyk** [comment]
@DevManifest I've made a PR as we are wanting this functionality as well:
https://github.com/hmaidasani/RadialChartImageGenerator/pull/8

**Comment by hmaidasani** [comment]
Thanks for the changes. Merged.
